on:
  push:
    branches: [main]
jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: Preview
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      - run: npm ci
      - run: vercel env ls
